spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(YMxB1K3oIL1YUlRa68rfHBFrb4YtYyFZ6ikB4bMkp+evYWBctHcpbJfuH+H3EJ0pnt0VSzTlbFgR68uZ9YOkyBNShgxTTkb+GDfV4kFTJlfpvDBzx09qqCS0ckyo0oGZb1L2QBsVYbA=)
    username: ENC(KAR1dpuSZ7Ucf8D3TfX11g7FPIelZ0yS)
    password: ENC(JEFlteVuCW6ylc5lN/c/l8Cjeu4phffu)

  data:
    redis:
      host: ENC(MM5dPI90nQGS6Rh1V/iaRZ70qDKyC4YY)
      port: 6379
      password:

  flyway:
    enabled: true
    baseline-on-migrate: true