spring:
  profiles:
    active:
      - prods
    group:
      locals:
        - local
        - core
        - secret
      prods:
        - prod
        - core
        - secret
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
