spring:
  profiles:
    active:
      - prods
    group:
      locals:
        - local
        - core
        - secret
      prods:
        - prod
        - core
        - secret

logging:
  level:
    root: DEBUG