springdoc:
  swagger-ui:
    path: /swagger-localmood.html

client-url: ENC(VcIPRmFCgEP+c3D4wTJJXZk1mP0bUGSNJc5id+l3pQqHsVKhEdXPVA==)
domain: ENC(Yeto6VIB1dp5To9oAijPbqc0C+syeRcRhXMnMFwLMJ8qx+irhVWKNHjW9r79+J0BfHWMGn1m9N88dG1Lk868Rg==)